import { ArrowRight, ClipboardList, FileSearch, Search, ShieldCheck } from 'lucide-react';
import { useState } from 'react';
import { Button } from '../../components/ui/button';
import { Card } from '../../components/ui/card';

type Props = { onSubmit: (message: string) => void; onLeave: () => void; onStatus: () => void; busy?: boolean };

export function Home({ onSubmit, onLeave, onStatus, busy }: Props) {
  const [message, setMessage] = useState('');
  function submit() { const value = message.trim(); if (!value || busy) return; onSubmit(value); }
  return <div className="space-y-6"><section className="border border-border bg-white p-6 md:p-8"><div className="flex flex-col gap-5 border-b border-border pb-6 md:flex-row md:items-end md:justify-between"><div><p className="text-sm font-medium text-service">高校学生事务统一服务</p><h1 className="mt-2 text-[28px] font-semibold tracking-tight md:text-4xl">学事智办 · 学生事务服务</h1><p className="mt-3 text-[15px] text-muted-foreground">查询制度、办理请假、跟进申请进度，都从这里开始。</p></div><p className="text-right text-sm text-muted-foreground"><span className="font-mono-data text-xs tracking-widest">STANDARDIZED SERVICE</span><br /><span className="font-medium text-foreground">问得清 · 办得稳 · 查得到</span></p></div>
    <div className="mt-6 bg-panel p-5"><div className="mb-3 flex items-center justify-between gap-4"><h2 className="flex items-center gap-2 text-lg font-semibold"><Search size={20} className="text-service" />今天想办理什么？</h2><span className="hidden text-xs text-muted-foreground sm:inline">通过 Main Agent 识别服务入口</span></div><div className="flex flex-col gap-3 sm:flex-row"><input value={message} onChange={(event) => setMessage(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter') submit(); }} placeholder="请描述你的问题或事务……" className="h-12 min-w-0 flex-1 rounded border border-border bg-white px-4 text-[15px] outline-none" /><Button className="h-12 min-w-28" onClick={submit} disabled={!message.trim() || busy}>{busy ? '正在识别…' : <>开始 <ArrowRight size={17} /></>}</Button></div><div className="mt-4 flex flex-wrap items-center gap-2 text-xs"><span className="text-muted-foreground">示例：</span>{['请假四天谁审批？', '我生病了，需要请假', '查询 DEMO-APP-XXXX 的状态'].map((example) => <button key={example} onClick={() => setMessage(example)} className="rounded bg-white px-2 py-1 text-service hover:bg-slate-50">{example}</button>)}</div></div>
  </section>
  <section className="grid gap-6 lg:grid-cols-12"><Card className="p-6 lg:col-span-7"><div className="flex items-center gap-2 text-sm font-medium"><span className="size-2 bg-primary" />重点业务通道</div><h2 className="mt-5 text-2xl font-semibold">请假办理</h2><p className="mt-3 max-w-xl text-[15px] leading-7 text-muted-foreground">填写信息后先生成审批预览；只有本人明确确认，才会创建并提交一份受控 DEMO 申请。</p><div className="mt-6 grid gap-3 bg-panel p-4 sm:grid-cols-4">{['填写信息', '审批预览', '确认提交', '办理完成'].map((step, index) => <div key={step}><span className="text-xs text-muted-foreground">第 {index + 1} 步</span><p className="mt-1 text-sm font-medium">{step}</p></div>)}</div><Button className="mt-6" onClick={onLeave}><ClipboardList size={17} />开始办理请假</Button></Card>
    <Card className="p-6 lg:col-span-5"><h2 className="flex items-center gap-2 text-lg font-semibold"><ShieldCheck size={19} className="text-service" />服务边界</h2><dl className="mt-5 space-y-4 text-sm"><Row label="制度咨询" value="官方知识库" /><Row label="请假写入" value="确认后执行" /><Row label="状态查询" value="只读" /></dl><Button variant="outline" className="mt-6" onClick={onStatus}><FileSearch size={17} />查询申请状态</Button></Card></section>
  </div>;
}
function Row({ label, value }: { label: string; value: string }) { return <div className="flex items-center justify-between border-b border-border pb-3"><dt className="text-muted-foreground">{label}</dt><dd className="font-medium">{value}</dd></div>; }
